### ISSUE TITLE
Feature request: Using runes for teleports where possible

### ISSUE THREAD

**Issue by HxxxxxS** [Speaax/Farming-Helper#1]
Hello, I am fairly new to the game and as such has not unlocked some of the teleporting options your plugin suggests using. Namely Portal Nexus, Explorers ring >1, Jewelery Box, Seed Pod. I would love if there was an option for just using normal teleports where possible, and Fairy Ring for the Farming Guild.

**Comment by Speaax** [comment]
Hey, sorry for a late response, didn't realize someone had written anything here. Ended up being a little burnt out trying to learn and figure everything out.

Adding new teleport options is fairly easy and I have started adding the code for a few new teleports. The fairy ring might not make it this update, depends on how much resistance i meet trying to implement it

Leagues 4 is releasing soon, so I'm not sure if I'll manage to add a lot more before that, but I will try and at least add a few more options for Herb runs for now.

**Comment by Speaax** [comment]
Added a few more teleport options with runes/tele tabs. Let me know if there is more teleport with runes/tabs I missed that you would find useful. Spirit tree/fairy ring will have to wait for now unfortunately, but I added skills necklace for farming guild.
