### ISSUE TITLE
spirit trees in place of seed pods

### ISSUE THREAD

**Issue by ZorbakScape** [Speaax/Farming-Helper#2]
maybe have spirit trees for gnome area instead of seed pods as a alternative

**Comment by ZorbakScape** [comment]
might be able to do it myself after looking at the code

**Comment by Speaax** [comment]
Hello, sorry i haven't been active lately with this plugin as i got a little burnt out on learning to code. But I will try and add in a few more teleport options before League 4 is released. Spirit tree is something I would like to have, but I might have some issues with it. But I will see if i cant get it in an update before Leagues 4 is out, or else it might have to wait until Leagues are over.

**Comment by othyn** [comment]
I would also love this option too!

**Comment by othyn** [comment]
Submitted a partially working PR for this.

It works and allows you to complete the run using Spirit Trees as an option, it just doesn't highlight the teleport option in the overly _or_ highlight the Spirit Tree object in the world. Mainly as I couldn't find info on how to get that ID from Google/DDG, should try ChatGPT I suppose.
