### ISSUE TITLE
Add Farming guild teleport option - Fairy Ring

### ISSUE THREAD

**Issue by ashwalk33r** [Speaax/Farming-Helper#32]
![image](https://github.com/Speaax/Farming-Helper/assets/58489098/dcc5331c-9341-40f0-94e2-0499ea765a4b)

None of listed Farming guild teleport options are available to me yet I reach Farming guild easily with Fairy rings (code "cir").

I recommend to add it.

**Comment by Speaax** [comment]
This was on the todo list. but I haven't been active developing this plugin for a while. Hopefully I'll find the motivation to keep developing the plugin soon, but I can't promise anything for now.
